AllCops:
  TargetRubyVersion: 2.2
  
Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Style/FileName:
  Exclude:
    - 'app/email-parser/AGRIUAUK.rb'
