app:
    data: '.data'
google:
    googleapis_host: https://www.googleapis.com
    client_id: <%= ENV['GOAUTH_CLIENT_ID'] %>
    client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
ledger:
    api_host: https://staging.my-ledger.com
log:
    stdout:
        enabled: true
        level: :debug
    file:
        enabled: true
        level: :debug
        path: log/service.log
    syslog:
        name: email-handler
        ident: service.plain.development.ledger.email-handler
        enabled: false
