google:
    googleapis_host: https://www.googleapis.com
    client_id: 127152602937-gpr5s8uce59ldqcqmivaf6ok0ksiovs5.apps.googleusercontent.com
    client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
log:
    stdout:
        enabled: true
        level: :debug
    file:
        enabled: true
        level: :debug
        path: log/service.log
