google:
    googleapis_host: http://localhost:43221
    client_id: fake-client-id-23312123.apps.googleusercontent.com
    client_secret: fake-secret-23312123
ledger:
    api_host: https://test.my-ledger.com
log:
    stdout:
        enabled: false
    file:
        path: log/test.log
